-   id: json-schema-description-filler
    name: json-schema-description-filler 
    description: Primarily intended to fill in missing description fields in BigQuery json schema files. Uses matching name fields to search if description is filled in another file for the same column.
    entry: /app
    language: docker
    pass_filenames: false
    require_serial: true
